### ISSUE TITLE
compile errors while installing; eventually found solution but you might want to document it

### ISSUE THREAD

**Issue by nonchip** [torch/cutorch#814]
tried to install it using the luarocks wrapper https://gist.github.com/nonchip/2c93ff2d9bc1bf2cd12bc6e76010da0f (essentially just setting the right environment for cuda etc) i get the following errors (omitting output of cmake before them):

```
[  6%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
2 errors detected in the compilation of "/tmp/tmpxft_000006f0_00000000-7_THCBlas.cpp1.ii".
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
CMake Error at THC_generated_THCBlas.cu.o.Release.cmake:279 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-9RB3n2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
make[2]: *** [lib/THC/CMakeFiles/THC.dir/build.make:72: lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
2 errors detected in the compilation of "/tmp/tmpxft_000006e9_00000000-7_THCSleep.cpp1.ii".
CMake Error at THC_generated_THCSleep.cu.o.Release.cmake:279 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-9RB3n2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCSleep.cu.o
make[2]: *** [lib/THC/CMakeFiles/THC.dir/build.make:79: lib/THC/CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o] Error 1
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
2 errors detected in the compilation of "/tmp/tmpxft_00000705_00000000-7_THCReduceApplyUtils.cpp1.ii".
CMake Error at THC_generated_THCReduceApplyUtils.cu.o.Release.cmake:279 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-9RB3n2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
make[2]: *** [lib/THC/CMakeFiles/THC.dir/build.make:65: lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
2 errors detected in the compilation of "/tmp/tmpxft_00000715_00000000-7_THCStorageCopy.cpp1.ii".
CMake Error at THC_generated_THCStorageCopy.cu.o.Release.cmake:279 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-9RB3n2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
make[2]: *** [lib/THC/CMakeFiles/THC.dir/build.make:93: lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
2 errors detected in the compilation of "/tmp/tmpxft_00000736_00000000-7_THCHalf.cpp1.ii".
CMake Error at THC_generated_THCHalf.cu.o.Release.cmake:279 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-9RB3n2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o
make[2]: *** [lib/THC/CMakeFiles/THC.dir/build.make:562: lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_00000724_00000000-7_THCStorage.cpp1.ii".
CMake Error at THC_generated_THCStorage.cu.o.Release.cmake:279 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-9RB3n2/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
make[2]: *** [lib/THC/CMakeFiles/THC.dir/build.make:86: lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Error: Build error: Failed building.
```

all dependencies of torch and cutorch are installed according to their documentation.

versions that might be important:
```
CUDA: 8.0
glibc: 2.26
gcc: 7.3.0
luajit: 2.0.5
luarocks: 2.4.3
kernel: Linux t1.nonchip.de 4.14.12_4 #1 SMP PREEMPT Mon Jan 8 11:05:24 UTC 2018 x86_64 GNU/Linux
```

**Comment by nonchip** [comment]
a very hacky "solution" I found was modifying `/usr/include/bits/floatn.h` by inserting this after the preprocessor switch that sets `__HAVE_FLOAT128`:
```
#if CUDART_VERSION
#undef __HAVE_FLOAT128
#define __HAVE_FLOAT128 0
#endif
```
but I'd rather prefer not abusing system includes to patch for what seems to be a broken usage of cuda types...

also it introduces another error occurring the same at about 10 different instances:
```
/usr/include/c++/7.3/bits/move.h(48): error: identifier "__builtin_addressof" is undefined
          detected during:
            instantiation of "_Tp *std::__addressof(_Tp &) [with _Tp=std::pair<const int, size_t>]"
/usr/include/c++/7.3/bits/stl_tree.h(225): here
            instantiation of "_Val *std::_Rb_tree_node<_Val>::_M_valptr() [with _Val=std::pair<const int, size_t>]"
/usr/include/c++/7.3/bits/stl_tree.h(278): here
            instantiation of "std::_Rb_tree_iterator<_Tp>::reference std::_Rb_tree_iterator<_Tp>::operator*() const [with _Tp=std::pair<const int, size_t>]"
/usr/include/c++/7.3/bits/stl_map.h(491): here
            instantiation of "std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type &std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const std::map<_Key, _Tp, _Compare, _Alloc>::key_type &) [with _Key=int, _Tp=size_t, _Compare=std::less<int>, _Alloc=std::allocator<std::pair<const int, size_t>>]"
/opt/cuda-8.0/include/thrust/system/cuda/detail/cub/util_allocator.cuh(414): here
```

and I'm afraid while hacking `/usr/include/bits` is ugly enough, I can't do much about missing builtins...

also, yes, I'm aware this seems to be a problem with cuda, but the strange thing is every other cuda based software I use works just fine.

not to compare with tensorflow ofcourse, which just barfs errors all over you when trying to compile on anything newer than ubuntu14.04 :P

but still, I like torch really much and would love to get it running (WITH cuda support, because neural networks on CPU are virtually impossible :P) on this system, and if I can provide any more information, please tell :)

**Comment by nonchip** [comment]
tried with cuda 9.1, same error.
both cuda versions, when trying clang instead of gcc, fail because `The version ('50001') of the host compiler ('clang') is not supported`

**Comment by nonchip** [comment]
ok, **figured it out**, a working combination of versions and ugly hacks is described at https://gist.github.com/nonchip/2c93ff2d9bc1bf2cd12bc6e76010da0f#file-cuda_and_current_compilers-md

seems to be just NVIDIA being archaic with their supported compilers; but you might want to include this somewhere in the documentation, for people using OS versions newer than 4 years :P
