### ISSUE TITLE
Compiler error running with "luarocks install cutorch"    on Jetson X1

### ISSUE THREAD

**Issue by sunyiyou** [torch/cutorch#513]
Well, I have been trying to run  "luarocks install cutorch"  on Jetson X1. I don't know how to fix this and have not searched some relative messages on web.

some configuration message is showing here:
-------------------------------------------------------------------------------------------------------------
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/ubuntu/torch/install
-- Found CUDA: /usr/local/cuda-7.0 (found suitable version "7.0", minimum required is "6.5") 
-- MAGMA not found. Compiling without MAGMA support
-- Autodetected CUDA architecture(s): 5.3
-- got cuda version 7.0
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -gencode;arch=compute_53,code=sm_53;-DCUDA_HAS_FP16=1
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-1543/cutorch/build

............................................................................................................................

[ 83%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/generated/./THC_generated_THCTensorMaskedDouble.cu.o
Scanning dependencies of target THC
[ 84%] [ 85%] [ 86%] [ 88%] Building C object lib/THC/CMakeFiles/THC.dir/THCAllocator.c.o
Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingAllocator.cpp.o
Building C object lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCStorage.c.o
In file included from /usr/include/c++/4.8/mutex:35:0,
                 from /tmp/luarocks_cutorch-scm-1-1543/cutorch/lib/THC/THCCachingAllocator.cpp:6:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
[ 89%] Building C object lib/THC/CMakeFiles/THC.dir/THCStorageCopy.c.o
/tmp/luarocks_cutorch-scm-1-1543/cutorch/lib/THC/THCCachingAllocator.cpp: In function ‘bool {anonymous}::BlockComparator(const {anonymous}::Block*, const {anonymous}::Block*)’:
/tmp/luarocks_cutorch-scm-1-1543/cutorch/lib/THC/THCCachingAllocator.cpp:50:13: error: ‘uintptr_t’ was not declared in this scope
     return (uintptr_t)a->stream < (uintptr_t)b->stream;
             ^
/tmp/luarocks_cutorch-scm-1-1543/cutorch/lib/THC/THCCachingAllocator.cpp:50:23: error: expected ‘;’ before ‘a’
     return (uintptr_t)a->stream < (uintptr_t)b->stream;
                       ^
/tmp/luarocks_cutorch-scm-1-1543/cutorch/lib/THC/THCCachingAllocator.cpp:50:46: error: expected ‘;’ before ‘b’
     return (uintptr_t)a->stream < (uintptr_t)b->stream;
                                              ^
/tmp/luarocks_cutorch-scm-1-1543/cutorch/lib/THC/THCCachingAllocator.cpp:55:11: error: ‘uintptr_t’ was not declared in this scope
   return (uintptr_t)a->ptr < (uintptr_t)b->ptr;
        ^
............................................................

       auto cur = it;
              ^
/tmp/luarocks_cutorch-scm-1-1543/cutorch/lib/THC/THCCachingAllocator.cpp:246:22: error: ‘cur’ was not declared in this scope
         blocks.erase(cur);
                      ^
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THCCachingAllocator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
--------------------------------------------------------------------------------------------------
This problem has bothered me for a long time. Is there anyone who can help me?

**Comment by szagoruyko** [comment]
yeah cutorch builds on Ubuntu 16.04, but not on 14.04. You can do this for now:
```
CMAKE_CXX_FLAGS="-std=c++11" luarocks install cutorch
```

**Comment by sunyiyou** [comment]
@szagoruyko Sadly,  it throw out with the same mistake as mentioned before. I found that if I run with "luarocks install cutorch". The "cutorch-scm-1.rockspec" file will be dowloaded from http://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec. The content is listed as fellow:
'''
package = "cutorch"
version = "scm-1"

source = {
   url = "git://github.com/torch/cutorch.git",
}

description = {
   summary = "Torch CUDA Implementation",
   detailed = [[
   ]],
   homepage = "https://github.com/torch/cutorch",
   license = "BSD"
}

dependencies = {
   "torch >= 7.0",
}

build = {
   type = "command",
   build_command = [[
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(LUA_BINDIR)/.." -DCMAKE_INSTALL_PREFIX="$(PREFIX)" && $(MAKE) -j$(getconf _NPROCESSORS_ONLN) install
]],
   install_command = "cd build"
}
'''

From the file you can see that this sentence "cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(LUA_BINDIR)/.." -DCMAKE_INSTALL_PREFIX="$(PREFIX)" && $(MAKE) -j$(getconf _NPROCESSORS_ONLN) install" does not have the choice flag of "-DCMAKE_CXX_FLAGS=".

Therefore, although I run with the "CMAKE_CXX_FLAGS="-std=c++11" luarocks install cutorch" as you suggested, this does not work and finally throw the same error message.

So what should I do now, could you give me some advice? Thanks for that :).

**Comment by soumith** [comment]
there is a fix incoming for this in 5 minutes. sorry about this.

**Comment by soumith** [comment]
this should now be fixed.

luarocks install cutorch

**Comment by sunyiyou** [comment]
I will response that as quickly as possible.

**Comment by sunyiyou** [comment]
Successfully installed cutorch. 👍 
Meanwhile, I also found that running with ( CMAKE_CXX_FLAGS="-std=c++11" luarocks make /rocks/cutorch-scm-1.rockspec) could fix it, too. 
All thanks.
